name: Mirror and run GitLab CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Mirror + trigger CI
        uses: SvanBoxel/gitlab-mirror-and-ci-action@master
        with:
          args: "https://git.bluebirdday.nl/shopify/amefa"
        env:
          FOLLOW_TAGS: "false"
          FORCE_PUSH: "false"
          GITLAB_HOSTNAME: "git.bluebirdday.nl"
          GITLAB_USERNAME: "koenpijnenburg@bluebirdday.nl"
          GITLAB_PASSWORD: ${{ secrets.GITLAB_ACCESS_KEY }}
          GITLAB_PROJECT_ID: "797"
